name: flutter_movil2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.5.0
  speech_to_text: ^6.3.0
  flutter_tts: ^3.4.0
  flutter_gemini: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
